### ISSUE TITLE
Failed test:  1) "before each" hook for "should emit deployed event"

### ISSUE THREAD

**Issue by alexrmacleod** [dOrgTech/OpenRaise#107]
1 test failed after running yarn test. 

how to fix this? what is the issue?

kind regards,

<img width="712" alt="Screen Shot 2021-06-13 at 2 54 15 PM" src="https://user-images.githubusercontent.com/7895493/121798151-482c0e80-cc57-11eb-8ab1-0b53773d4d4a.png">

```89 passing (4m)
  1 failing

  1) Contract: BondingCurveFactory
       Deploy BancorCurveLogic + ERC20 Collateral
         "before each" hook for "should emit deployed event":
     Error: Returned error: VM Exception while processing transaction: revert
      at Object.ErrorResponse (node_modules/@openzeppelin/upgrades/node_modules/web3-core-helpers/src/errors.js:29:16)
      at /Users/alex/Documents/OpenRaise/node_modules/@openzeppelin/upgrades/node_modules/web3-core-requestmanager/src/index.js:140:36
      at /Users/alex/Documents/OpenRaise/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:107:1
      at XMLHttpRequest.request.onreadystatechange (node_modules/truffle/build/webpack:/node_modules/web3/node_modules/web3-providers-http/lib/index.js:98:1)
      at XMLHttpRequestEventTarget.dispatchEvent (node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
      at XMLHttpRequest.exports.modules.996763.XMLHttpRequest._setReadyState (node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:208:1)
      at XMLHttpRequest.exports.modules.996763.XMLHttpRequest._onHttpResponseEnd (node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:318:1)
      at IncomingMessage.<anonymous> (node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:289:47)
      at endReadableNT (_stream_readable.js:1145:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)



error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
alex@HL072 OpenRaise % 
```

**Comment by dOrgJelli** [comment]
Hey @alexrmacleod, this repo has just been archived (should have been sooner). The contracts were never fully finished or audited. Please feel free to fork and continue as you see fit!
